spring:
  jackson:
    time-zone: UTC
    deserialization:
      adjust-dates-to-context-time-zone: false
  datasource:
    url: jdbc:sqlite:C:/dev/Arduino-UNO-R4-Communication-backend-SQLite/arduino-communication-endpoints/ArduinoTestDB.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
